import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import About from './about-me';
import Loader from './components/Loader';

export default function Home() {
	const router = useRouter();
	const list = [
		{ title: 'frontend' },
		{ title: 'web' },
		{ title: 'developer' },
	];
	const [isLoading, setIsLoading] = useState(false);

	useEffect(() => {
		setIsLoading(true);
		setTimeout(() => {
			setIsLoading(false);
		}, 0.3 * 1000);
	}, []);

	if (isLoading) {
		return <Loader />;
	}

	return (
		<div className=''>
			<Head>
				<title>my-portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/images/hero-image.jpg' />
			</Head>

			<main className='w-full pt-[10vh] px-4 min-h-[80vh] '>
				<div className='container flex flex-col-reverse  md:flex-row items-center justify-between w-full min-h-[80vh]'>
					<section className='left flex-1 flex flex-col items-center sm:items-start justify-between gap-5 md:text-gray-700 text-gray-100 overflow-hidden pt-5 min-h-[300px] md:h-[70vh] absolute top-[10rem] md:relative md:top-0 z-40 bg-gray-600/70 md:bg-inherit py-6 px-6 mx-6 sm:mx-16 md:mx-auto rounded-lg   '>
						<h1 className=' text-blue-300 md:text-blue-500 text-center sm:text-start '>
							hie,{' '}
							<span className=' animate-fade-in block  '>
								I am Blessings Butao
							</span>
							<span className=' text-center text-5xl mt-4 h-[50px] items-center   overflow-hidden flex-col  flex '>
								{list.map((li, index) => (
									<span
										key={index}
										className='
											animate-draw-top block self-start
                              py-1 text-red-300 md:text-red-600  sm:bg-slate-200 text-center font-fila '
									>
										{li.title}
									</span>
								))}
							</span>
						</h1>
						<p>for your online presence and all web solution contact us</p>
						<button
							className=' w-[160px] py-2 rounded-md bg-purple-400 shadow-md hover:bg-purple-300 hover:border hover:text-gray-500  border-slate-300 border-2 text-inherit transition-all ease-out duration-100 self-center delay-75 sm:self-start z-50 '
							onClick={() => router.push('/contact')}
						>
							hire me
						</button>
					</section>

					<section className='flex-1 h-[400px] rounded-md z-30 overflow-hidden bg-black md:bg-inherit lg:h-[70vh] w-full  relative before:absolute before:inset-0 before:bg-black/50 before:z-50'>
						<Image
							src='/images/hero-image.jpg'
							alt='hero-image'
							layout='fill'
							objectFit='cover'
							className=' '
						/>
					</section>
				</div>
			</main>
			<About />
		</div>
	);
}
