import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
	const list = [
		{ title: 'frontend' },
		{ title: 'web' },
		{ title: 'developer' },
	];
	const color = {
		blue: '#00bcd4',
		red: '#ff0000',
		green: '#00ff00',
	};

	return (
		<div className=''>
			<Head>
				<title>my-portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.jpg' />
			</Head>

			<main className='w-full px-4 min-h-[80vh] '>
				<div className='container flex flex-col-reverse md:flex-row items-center justify-between w-full min-h-[80vh]'>
					<section className='left flex-1 flex flex-col items-start justify-between gap-5 text-gray-700 overflow-hidden  '>
						<h1 className='text-blue-500 text-3xl '>
							hie,{' '}
							<span className=' animate-fade-in block '>
								I am Blessings Butao
							</span>
							<span className=' text-5xl mt-4 h-[50px] items-center   overflow-hidden flex-col  flex '>
								{list.map((li, index) => (
									<span
										key={index}
										className='
											animate-draw-top block self-start
                              py-1 text-red-500 bg-slate-200'
									>
										{li.title}
									</span>
								))}
							</span>
						</h1>
						<p>
							Lorem ipsum dolor, sit amet consectetur adipisicing elit. Totam,
							neque enim natus facere sint aperiam amet sed
						</p>
						<button className=' border px-5 py-2 rounded-md text-purple-400 shadow-md hover:bg-purple-100 hover:border hover:text-gray-500 border-white text-inherit transition-all ease-out duration-100 delay-75 '>
							hire me
						</button>
					</section>
					<section className='flex-1 h-[300px] md:h-[70vh] w-full  relative'>
						<Image
							src='/images/image-hero.png'
							alt='hero-image'
							layout='fill'
							objectFit='cover'
							className=' hover:animate-fade-out'
						/>
					</section>
				</div>
			</main>
		</div>
	);
}
