import Head from 'next/head';

export default function Home() {
	return (
		<div className=''>
			<Head>
				<title>my-portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<h1 className=' text-red-500 '>hello worl</h1>
			<h2>helo9</h2>
		</div>
	);
}
